version: '2'
services:
    mongo-5-2:
        container_name: "mongo-5-2"
        image: mongo:3.4
        expose:
            - "27017"
        command: mongod --replSet rs5 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 0.5
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-5-arb:
        container_name: "mongo-5-arb"
        image: mongo:3.4
        expose:
            - "27017"
        command: mongod --replSet rs5 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-5-1:
        container_name: "mongo-5-1"
        image: mongo:3.4
        expose:
            - "27017"
        command: mongod --replSet rs5 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 2
        links:
            - mongo-5-2:mongo-5-2
            - mongo-5-arb:mongo-5-arb
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary

    mongo-rs5-setup:
        container_name: "mongo-rs5-setup"
        image: mgbi/mongo-setup:3.4
        depends_on:
            - "mongo-5-1"
            - "mongo-5-2"
            - "mongo-5-arb"
        links:
            - mongo-5-1:mongo-5-1
            - mongo-5-2:mongo-5-2
            - mongo-5-arb:mongo-5-arb
        environment: 
            - MONGO1=mongo-5-1
            - MONGO2=mongo-5-2
            - MONGOARB=mongo-5-arb
            - RS=rs5
        entrypoint: [ "/scripts/setup.sh" ]
        labels:
            io.rancher.container.start_once: "true"
            io.rancher.scheduler.affinity:host_label: members=primary
