version: '2'
services:
    mongo-8-2:
        container_name: "mongo-8-2"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs8 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 0.5"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-8-arb:
        container_name: "mongo-8-arb"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs8 --shardsvr --port 27017 --oplogSize 16"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-8-1:
        container_name: "mongo-8-1"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs8 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 2"
        links:
            - mongo-8-2:mongo-8-2
            - mongo-8-arb:mongo-8-arb
        environment: 
            - MONGO1=mongo-8-1
            - MONGO2=mongo-8-2
            - MONGOARB=mongo-8-arb
            - RS=rs8
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary
