version: '2'
services:
    mongo-6-2:
        container_name: "mongo-6-2"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs6 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 0.5"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-6-arb:
        container_name: "mongo-6-arb"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs6 --shardsvr --port 27017 --oplogSize 16"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-6-1:
        container_name: "mongo-6-1"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs6 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 2"
        links:
            - mongo-6-2:mongo-6-2
            - mongo-6-arb:mongo-6-arb
        environment: 
            - MONGO1=mongo-6-1
            - MONGO2=mongo-6-2
            - MONGOARB=mongo-6-arb
            - RS=rs6
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary
