version: '2'
services:
    mongo-1-2:
        container_name: "mongo-1-2"
        image: mongo:3.4
        expose:
            - "27017"
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 0.5
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-1-arb:
        container_name: "mongo-1-arb"
        image: mongo:3.4
        expose:
            - "27017"
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo:3.4
        expose:
            - "27017"
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 2
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-arb:mongo-1-arb
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: mgbi/mongo-setup:3.4
        depends_on:
            - "mongo-1-1"
            - "mongo-1-2"
            - "mongo-1-arb"
        links:
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-arb:mongo-1-arb
        environment: 
            - MONGO1=mongo-1-1
            - MONGO2=mongo-1-2
            - MONGOARB=mongo-1-arb
            - RS=rs1
        entrypoint: [ "/scripts/setup.sh" ]
        labels:
            io.rancher.container.start_once: "true"
            io.rancher.scheduler.affinity:host_label: members=primary
