version: '2'
services:
    mongo-5-2:
        container_name: "mongo-5-2"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs5 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 0.5"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-5-arb:
        container_name: "mongo-5-arb"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs5 --shardsvr --port 27017 --oplogSize 16"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-5-1:
        container_name: "mongo-5-1"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs5 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 2"
        links:
            - mongo-5-2:mongo-5-2
            - mongo-5-arb:mongo-5-arb
        environment: 
            - MONGO1=mongo-5-1
            - MONGO2=mongo-5-2
            - MONGOARB=mongo-5-arb
            - RS=rs5
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary
