version: '2'
services:
    mongo-2-2:
        container_name: "mongo-2-2"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH}
                mongod --keyFile ${KEYFILE_PATH} \
                    --replSet rs2 --shardsvr --port 27017 --oplogSize 16 \
                    --noprealloc --smallfiles --wiredTigerCacheSizeGB 0.5"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-2-arb:
        container_name: "mongo-2-arb"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH}
                mongod --keyFile ${KEYFILE_PATH} \
                    --replSet rs2 --shardsvr --port 27017 --oplogSize 16 \
                    --noprealloc --smallfiles"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-2-1:
        container_name: "mongo-2-1"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH}
                mongod --keyFile ${KEYFILE_PATH} \
                    --replSet rs2 --shardsvr --port 27017 --oplogSize 16 \
                    --noprealloc --smallfiles --wiredTigerCacheSizeGB 2"
        links:
            - mongo-2-2:mongo-2-2
            - mongo-2-arb:mongo-2-arb
        environment: 
            - MONGO1=mongo-2-1
            - MONGO2=mongo-2-2
            - MONGOARB=mongo-2-arb
            - RS=rs2
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary
