version: '2'
services:
    mongo-6-2:
        container_name: "mongo-6-2"
        image: mongo:3.4
        ports:
            - "30062:27017"
        command: mongod --replSet rs6 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 0.5
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-6-arb:
        container_name: "mongo-6-arb"
        image: mongo:3.4
        ports:
            - "30063:27017"
        command: mongod --replSet rs6 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-6-1:
        container_name: "mongo-6-1"
        image: mongo:3.4
        ports:
            - "30061:27017"
        command: mongod --replSet rs6 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 2
        links:
            - mongo-6-2:mongo-6-2
            - mongo-6-arb:mongo-6-arb
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary

    mongo-rs6-setup:
        container_name: "mongo-rs6-setup"
        image: mgbi/mongo-setup:3.4
        depends_on:
            - "mongo-6-1"
            - "mongo-6-2"
            - "mongo-6-arb"
        links:
            - mongo-6-1:mongo-6-1
            - mongo-6-2:mongo-6-2
            - mongo-6-arb:mongo-6-arb
        environment: 
            - MONGO1=mongo-6-1
            - MONGO2=mongo-6-2
            - MONGOARB=mongo-6-arb
            - RS=rs6
        entrypoint: [ "/scripts/setup.sh" ]
        labels:
            io.rancher.container.start_once: "true"
            io.rancher.scheduler.affinity:host_label: members=primary
