version: '2'
services:
    mongo-7-2:
        container_name: "mongo-7-2"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs7 --shardsvr --port 27017 --oplogSize 32 --wiredTigerCacheSizeGB 0.5"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-7-arb:
        container_name: "mongo-7-arb"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs7 --shardsvr --port 27017 --oplogSize 32"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-7-1:
        container_name: "mongo-7-1"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs7 --shardsvr --port 27017 --oplogSize 32 --wiredTigerCacheSizeGB 2"
        links:
            - mongo-7-2:mongo-7-2
            - mongo-7-arb:mongo-7-arb
        environment:
            - MONGO1=mongo-7-1
            - MONGO2=mongo-7-2
            - MONGOARB=mongo-7-arb
            - RS=rs7
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary
