version: '2'
services:
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs-cnf --configsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 0.25"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs-cnf --configsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 0.25"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs-cnf --configsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 0.25"
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        environment:
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=rs-cnf
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary
