version: '2'
services:
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo:3.4
        ports:
            - "30102:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 0.25
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mongo:3.4
        ports:
            - "30103:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 0.25
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo:3.4
        ports:
            - "30101:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles --wiredTigerCacheSizeGB 0.25
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mgbi/mongo-setup:3.4
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
            - "mongo-cnf-3"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        environment: 
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]
        labels:
            io.rancher.container.start_once: "true"
            io.rancher.scheduler.affinity:host_label: members=primary
