version: '2'
services:
    mongo-4-2:
        container_name: "mongo-4-2"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs4 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 0.5"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-4-arb:
        container_name: "mongo-4-arb"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs4 --shardsvr --port 27017 --oplogSize 16"
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=secondary

    mongo-4-1:
        container_name: "mongo-4-1"
        image: mgbi/mongo-rs:${MONGO_VERSION}
        expose:
            - "27017"
        command: >
            sh -ce "
                get-replica-set-key ${REPLICA_KEY_URL} ${KEYFILE_PATH};
                mongod --keyFile ${KEYFILE_PATH} --replSet rs4 --shardsvr --port 27017 --oplogSize 16 --wiredTigerCacheSizeGB 2"
        links:
            - mongo-4-2:mongo-4-2
            - mongo-4-arb:mongo-4-arb
        environment: 
            - MONGO1=mongo-4-1
            - MONGO2=mongo-4-2
            - MONGOARB=mongo-4-arb
            - RS=rs4
        restart: on-failure
        labels:
            io.rancher.scheduler.affinity:host_label: members=primary
