#!/bin/bash 

mongodb1=`getent hosts ${MONGO1} | awk '{ print $1 }'`
mongodb2=`getent hosts ${MONGO2} | awk '{ print $1 }'`
mongodb3=`getent hosts ${MONGO3} | awk '{ print $1 }'`

port=${PORT:-27017}

for mongodb in $mongodb1 $mongodb2 $mongodb3; do
	echo "Waiting for ${mongodb} startup.."
  	until mongo --host ${mongodb}:${port} --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
		printf '.'
		sleep 1
	done
done

echo "Started.."


# Connect to the primary using the localhost interface
echo init-cnf-replica-set time now: `date +"%T" `
mongo --port ${port} <<EOF
   var cfg = {
        "_id": "${RS}",
        "configsvr": true,
        "protocolVersion": 1,
        "members": [
            {
                "_id": 100,
                "host": "${mongodb1}:${port}",
				"priority": 2
            },
            {
                "_id": 101,
                "host": "${mongodb2}:${port}",
				"priority": 1
            },
            {
                "_id": 102,
                "host": "${mongodb3}:${port}",
				"priority": 1
            }
        ]
    };
    rs.initiate(cfg, { force: true });
EOF
